# Find All
###
http://localhost:8001/workers

# Find By Id - 8001
###
http://localhost:8001/workers/1

# Find By Id - 8002
###
http://localhost:8002/workers/1

# Find All With Gateway-zull
###
http://localhost:8765/hr-worker/workers

# Find by id With Gateway-zuul
###
http://localhost:8765/hr-worker/workers/1

# Show worker configs on console
###
http://localhost:8765/hr-worker/workers/configs

# Actuator refresh
###
Post http://localhost:8765/hr-worker/actuator/refresh

# Find All With Gateway-zull with token of login
###
http://localhost:8765/hr-worker/workers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjMzNTgzODcsInVzZXJfbmFtZSI6ImxlaWFAZ21haWwuY29tIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9PUEVSQVRPUiIsIlJPTEVfQURNSU4iXSwianRpIjoiMTQ4YjgyMmUtZDUwMS00ZTAyLTg1MTEtYzY3ZTc3ZmY2ZmU5IiwiY2xpZW50X2lkIjoibXlhcHBuYW1lMTIzIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl19.vhVPTVUQLlbaXh1VnrligS8CS72ZU5gtyOBfRiAhRs8