# Payment
###
http://localhost:8101/payments/1/days/20

# Payment with gateway-zuul
###
http://localhost:8765/hr-payroll/payments/1/days/20

# Payment with gateway-zuul with token of login
###
http://localhost:8765/hr-payroll/payments/1/days/20
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjU0OTY2NDcsInVzZXJfbmFtZSI6ImxlaWFAZ21haWwuY29tIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9PUEVSQVRPUiIsIlJPTEVfQURNSU4iXSwianRpIjoiYWQ1YzY5MTMtNTM3Ni00ZWMzLWJhYjgtZDczOWZjMWZjYzUxIiwiY2xpZW50X2lkIjoibXlhcHBuYW1lMTIzIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl19.JwRDUwvwNvWjkSgt6bnW1IckXT61qsaDlfs6ni4_ZRE