# Payment
###
http://localhost:8101/payments/1/days/20

# Payment with gateway-zuul
###
http://localhost:8765/hr-payroll/payments/1/days/20

# Payment with gateway-zuul with token of login
###
http://localhost:8765/hr-payroll/payments/1/days/20
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjMzNjAwMDYsInVzZXJfbmFtZSI6ImxlaWFAZ21haWwuY29tIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9PUEVSQVRPUiIsIlJPTEVfQURNSU4iXSwianRpIjoiMTcwZDk3MGMtMWI5OC00YzdiLTljODQtYWI0YzE3M2IwNjc4IiwiY2xpZW50X2lkIjoibXlhcHBuYW1lMTIzIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl19.gGaN3SBtaa29mQjMO3-OihemuZthiMY_OgajY8ZPjek